//! Raw FFI bindings for QBDI C API (auto-generated by bindgen)

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(clippy::all)]

// Include bindgen-generated bindings
include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

// ============================================================================
// Manual definitions for types that bindgen can't handle
// ============================================================================

/// ARM64 Floating Point Register state
/// bindgen can't handle __uint128_t, so we define this manually
#[repr(C)]
#[repr(align(8))]
#[derive(Debug, Clone, Copy)]
pub struct FPRState {
    pub v0: u128,
    pub v1: u128,
    pub v2: u128,
    pub v3: u128,
    pub v4: u128,
    pub v5: u128,
    pub v6: u128,
    pub v7: u128,
    pub v8: u128,
    pub v9: u128,
    pub v10: u128,
    pub v11: u128,
    pub v12: u128,
    pub v13: u128,
    pub v14: u128,
    pub v15: u128,
    pub v16: u128,
    pub v17: u128,
    pub v18: u128,
    pub v19: u128,
    pub v20: u128,
    pub v21: u128,
    pub v22: u128,
    pub v23: u128,
    pub v24: u128,
    pub v25: u128,
    pub v26: u128,
    pub v27: u128,
    pub v28: u128,
    pub v29: u128,
    pub v30: u128,
    pub v31: u128,
    pub fpcr: rword,
    pub fpsr: rword,
}

impl Default for FPRState {
    fn default() -> Self {
        Self {
            v0: 0,
            v1: 0,
            v2: 0,
            v3: 0,
            v4: 0,
            v5: 0,
            v6: 0,
            v7: 0,
            v8: 0,
            v9: 0,
            v10: 0,
            v11: 0,
            v12: 0,
            v13: 0,
            v14: 0,
            v15: 0,
            v16: 0,
            v17: 0,
            v18: 0,
            v19: 0,
            v20: 0,
            v21: 0,
            v22: 0,
            v23: 0,
            v24: 0,
            v25: 0,
            v26: 0,
            v27: 0,
            v28: 0,
            v29: 0,
            v30: 0,
            v31: 0,
            fpcr: 0,
            fpsr: 0,
        }
    }
}

/// Opaque VM instance type
pub type VMInstance = core::ffi::c_void;
pub type VMInstanceRef = *mut VMInstance;

// ============================================================================
// Type aliases for convenience
// ============================================================================

/// Word type aliases
pub type RWord = rword;
pub type SWord = sword;

/// LocalMonitor type alias (bindgen generates this as anonymous struct)
pub type LocalMonitor = GPRState__bindgen_ty_1;

/// Permission type alias
pub type Permission = qbdi_Permission;

/// Permission constants
pub const PF_NONE: Permission = qbdi_Permission_QBDI_PF_NONE;
pub const PF_READ: Permission = qbdi_Permission_QBDI_PF_READ;
pub const PF_WRITE: Permission = qbdi_Permission_QBDI_PF_WRITE;
pub const PF_EXEC: Permission = qbdi_Permission_QBDI_PF_EXEC;

/// Invalid event ID constant
pub const INVALID_EVENTID: u32 = 0xffffffff;
